const $ = (q) => document.querySelector(q);
let match = null, analytics = null, session = JSON.parse(localStorage.getItem('cricpulse-session') || 'null');
const toast = (text) => { const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500); };
const authHeaders = () => session ? { Authorization: `Bearer ${session.token}` } : {};
async function load() {
  try { const [m,a]=await Promise.all([fetch('api/state').then(r=>r.json()),fetch('api/analytics').then(r=>r.json())]);match=m;analytics=a;render(); }
  catch { toast('Live score feed reconnecting…'); }
}
function render() {
  $('#score').innerHTML=`${match.score}<span>/${match.wickets}</span>`;$('#rolling-rate').innerHTML=`${analytics.rollingRunRate.toFixed(2)}<span> / over</span>`;$('#stretch').textContent=`BEST 6 OVERS　${analytics.bestSixOverRuns} RUNS`;
  const recent=match.overs.slice(-3).reduce((sum,o)=>sum+o.runs,0)/Math.min(3,match.overs.length);const innings=match.overs.reduce((sum,o)=>sum+o.runs,0)/match.overs.length;const delta=recent-innings;$('#last-three').textContent=recent.toFixed(2);$('#innings-average').textContent=innings.toFixed(2);$('#rate-delta').textContent=`${delta>=0?'+':'−'}${Math.abs(delta).toFixed(2)} vs innings avg`;
  let bestStart=0,bestRuns=-1;for(let start=0;start+6<=match.overs.length;start++){const runs=match.overs.slice(start,start+6).reduce((sum,o)=>sum+o.runs,0);if(runs>bestRuns){bestRuns=runs;bestStart=start;}}
  const max=Math.max(...match.overs.map(o=>o.runs));const bars=match.overs.map((o,i)=>`<div class="bar-col"><span class="bar-value" style="--height:${Math.round(o.runs/max*100)}%">${o.runs}</span><i class="bar ${i>=bestStart&&i<bestStart+6?'best':''}" style="height:${Math.max(5,o.runs/max*100)}%"></i><small class="bar-label">${o.number}</small></div>`).join('');$('#chart').innerHTML=bars;
  $('#mini-bars').innerHTML=match.overs.slice(-8).map(o=>`<i style="height:${Math.max(4,o.runs/24*36)}px"></i>`).join('');
  $('#feed-list').innerHTML=match.overs.slice(-6,-1).reverse().map(o=>`<div class="feed-row"><span>Over ${o.number}</span><b>${o.runs} runs</b></div>`).join('');
  renderGraph();
  if(session){$('#user-badge').textContent=session.user;$('#login-open').textContent='Sign out';$('#player-workspace').classList.toggle('hidden',session.role!=='player');$('#poll-options').classList.add('voted');}
  else {$('#user-badge').textContent='Guest';$('#login-open').textContent='Sign in';$('#player-workspace').classList.add('hidden');}
}
function renderGraph(){const players=[{id:0,x:10,y:51,initials:'RS',short:'Rohit',cl:'kohli'},{id:1,x:34,y:24,initials:'VK',short:'Kohli',cl:'kohli'},{id:2,x:34,y:78,initials:'SG',short:'Gill',cl:'other'},{id:3,x:59,y:18,initials:'SY',short:'Surya',cl:'pandya'},{id:4,x:68,y:75,initials:'HP',short:'Hardik',cl:'pandya'},{id:5,x:91,y:48,initials:'RJ',short:'Jadeja',cl:'jadeja'}];const edges=[{a:0,b:1,r:38},{a:0,b:2,r:30,strong:true},{a:0,b:3,r:14,weak:true},{a:1,b:5,r:20,weak:true},{a:2,b:4,r:45,strong:true},{a:3,b:4,r:22,weak:true},{a:4,b:5,r:34,strong:true}];let html='';for(const e of edges){const a=players[e.a],b=players[e.b],dx=b.x-a.x,dy=b.y-a.y,len=Math.sqrt(dx*dx+dy*dy),angle=Math.atan2(dy,dx)*180/Math.PI;html+=`<div class="graph-edge ${e.weak?'weak':''}" style="left:${a.x}%;top:${a.y}%;width:${len}%;transform:rotate(${angle}deg)"><span>${e.r}</span></div>`;}for(const p of players)html+=`<div class="graph-player" style="left:${p.x}%;top:${p.y}%"><span class="avatar ${p.cl}">${p.initials}</span><b>${p.short}</b><small>${p.id===0?'at crease':'batting link'}</small></div>`;$('#partnership-graph').innerHTML=html;}
$('#login-open').onclick=()=>{if(session){session=null;localStorage.removeItem('cricpulse-session');render();toast('Signed out');return;}$('#login-modal').classList.remove('hidden');};
$('#login-close').onclick=()=>$('#login-modal').classList.add('hidden');$('#account').onchange=()=>{$('#password').value=$('#account').value==='player'?'coverdrive':'fanpass';};
$('#login-submit').onclick=async()=>{const user=$('#account').value==='player'?'rohit':'fan';const response=await fetch('api/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`user=${user}&password=${encodeURIComponent($('#password').value)}`});const result=await response.json();if(!result.ok){toast('Sign-in details did not match');return;}session=result;localStorage.setItem('cricpulse-session',JSON.stringify(session));$('#login-modal').classList.add('hidden');render();toast(`Welcome, ${session.user}`);};
document.querySelectorAll('.poll-option').forEach(button=>button.onclick=async()=>{if(!session){$('#login-modal').classList.remove('hidden');toast('Sign in to cast your vote');return;}const r=await fetch('api/poll',{method:'POST',headers:{...authHeaders(),'Content-Type':'application/x-www-form-urlencoded'},body:`choice=${button.dataset.choice}`});const data=await r.json();toast(data.ok?'Your vote is in':data.error);});
$('#save-note').onclick=async()=>{const r=await fetch('api/player-note',{method:'POST',headers:{...authHeaders(),'Content-Type':'application/x-www-form-urlencoded'},body:`note=${encodeURIComponent($('#player-note').value)}`});const result=await r.json();toast(result.ok?'Player note saved':result.error);};
$('#password').onkeydown=(e)=>{if(e.key==='Enter')$('#login-submit').click();};load();setInterval(load,5000);
